#!/usr/bin/env bash

set -e

ARCH="$(uname -m)"
TOP=5

TMP="$(mktemp)"

MIRROR_URL="https://adrianpriza-ai.github.io/alps-more/chaotic-aur/chaotic-mirrorlist"

OUTPUT="/etc/pacman.d/chaotic-mirrorlist"

echo "[+] Downloading Chaotic-AUR mirrorlist..."

curl -fsSL "$MIRROR_URL" -o "$TMP"

echo
echo "[+] Benchmarking mirrors..."

grep '^Server' "$TMP" \
| sed 's|Server = ||' \
| while read -r raw; do

    test_url="${raw//\$arch/$ARCH}"
    test_url="${test_url//\$repo/chaotic-aur}"

    speed=$(
        curl \
            -o /dev/null \
            -s \
            -w "%{time_total}" \
            --connect-timeout 3 \
            --max-time 8 \
            "${test_url}/chaotic-aur.db" \
        2>/dev/null || echo "999"
    )

    echo "${speed}|${raw}"

done \
| sort -t'|' -k1,1g \
| head -n "$TOP" > "${TMP}.sorted"

echo
echo "[+] Best mirrors:"
cat "${TMP}.sorted"

echo
echo "[+] Writing optimized mirrorlist..."

{
    echo "## Generated by ALPS"
    echo

    cut -d'|' -f2 "${TMP}.sorted" \
    | while read -r line; do
        echo "Server = $line"
    done

} | sudo tee "$OUTPUT" >/dev/null

echo
echo "[+] Importing Chaotic-AUR keys..."

sudo pacman-key \
    --recv-key 3056513887B78AEB \
    --keyserver keyserver.ubuntu.com

sudo pacman-key --lsign-key 3056513887B78AEB

echo
echo "[+] Installing Chaotic-AUR keyring..."

sudo pacman -U --noconfirm \
    https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-keyring.pkg.tar.zst \
    https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-mirrorlist.pkg.tar.zst

echo
echo "[+] Adding repository to pacman.conf..."

if ! grep -q "^\[chaotic-aur\]" /etc/pacman.conf; then
    {
        echo
        echo "[chaotic-aur]"
        echo "Include = /etc/pacman.d/chaotic-mirrorlist"
    } | sudo tee -a /etc/pacman.conf >/dev/null
fi

echo
echo "[+] Syncing pacman..."

sudo pacman -Sy

echo
echo "[+] Chaotic-AUR setup complete."
