#!/usr/bin/env bash

set -e

ARCH="$(uname -m)"
TOP=5

TMP="$(mktemp)"

MIRROR_URL="https://adrianpriza-ai.github.io/alps-more/chaotic-aur/chaotic-mirrorlist"

OUTPUT="/etc/pacman.d/chaotic-mirrorlist"

echo "[+] Downloading mirrorlist..."

curl -fsSL "$MIRROR_URL" -o "$TMP"

echo
echo "[+] Benchmarking mirrors..."

grep '^Server' "$TMP" \
| sed 's|Server = ||' \
| while read -r url; do

    mirror="${url//\$arch/$ARCH}"
    mirror="${mirror//\$repo/chaotic-aur}"

    speed=$(
        curl \
            -o /dev/null \
            -s \
            -w "%{time_total}" \
            --connect-timeout 3 \
            --max-time 8 \
            "${mirror}/${ARCH}/" \
        2>/dev/null || echo "999"
    )

    echo "$speed $mirror"

done \
| sort -n \
| head -n "$TOP" > "${TMP}.sorted"

echo
echo "[+] Best mirrors:"
cat "${TMP}.sorted"

echo
echo "[+] Writing mirrorlist..."

{
    echo "## Generated by ALPS"
    echo

    awk '{print "Server = " $2}' "${TMP}.sorted"

} | sudo tee "$OUTPUT" >/dev/null

echo
echo "[+] Installing Chaotic-AUR keyring..."

sudo pacman-key \
    --recv-key 3056513887B78AEB \
    --keyserver keyserver.ubuntu.com

sudo pacman-key --lsign-key 3056513887B78AEB

sudo pacman -U --noconfirm \
    https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-keyring.pkg.tar.zst \
    https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-mirrorlist.pkg.tar.zst

echo
echo "[+] Adding repository to pacman.conf..."

if ! grep -q "^\[chaotic-aur\]" /etc/pacman.conf; then
    {
        echo
        echo "[chaotic-aur]"
        echo "Include = /etc/pacman.d/chaotic-mirrorlist"
    } | sudo tee -a /etc/pacman.conf >/dev/null
fi

echo
echo "[+] Syncing pacman..."

sudo pacman -Sy

echo
echo "[+] Chaotic-AUR setup complete."
