#!/usr/bin/env bash

set -e

ARCH="$(uname -m)"
TOP=5

TMP="$(mktemp)"
TMP_DIR=""

cleanup() {
    rm -f "$TMP" "${TMP}.sorted"
    if [[ -n "$TMP_DIR" && -d "$TMP_DIR" ]]; then
        rm -rf "$TMP_DIR"
    fi
}
trap cleanup EXIT

MIRROR_URL="https://adrianpriza-ai.github.io/alps-more/archlinuxcn/archlinuxcn-mirrorlist"

OUTPUT="/etc/pacman.d/archlinuxcn-mirrorlist"

echo "[+] Downloading archlinuxcn mirrorlist..."

curl -fsSL "$MIRROR_URL" -o "$TMP"

echo
echo "[+] Benchmarking mirrors in parallel..."

TMP_DIR="$(mktemp -d)"
count=0

grep '^Server' "$TMP" \
| sed 's|Server = ||' \
| while read -r raw; do
    count=$((count+1))
    (
        test_url="${raw//\$arch/$ARCH}"

        speed=$(
            curl \
                -o /dev/null \
                -s \
                -f \
                -w "%{time_total}" \
                --connect-timeout 3 \
                --max-time 8 \
                "${test_url}/archlinuxcn.db" \
            2>/dev/null || echo "999"
        )

        if [[ -n "$speed" && "$speed" != "999" ]]; then
            echo "${speed}|${raw}" > "$TMP_DIR/$count"
        fi
    ) &
done

wait || true

if ! ls "$TMP_DIR"/* &>/dev/null; then
    echo "[-] Error: No working mirrors found or connection timed out."
    exit 1
fi

cat "$TMP_DIR"/* 2>/dev/null \
| sort -t'|' -k1,1g \
| head -n "$TOP" > "${TMP}.sorted"

rm -rf "$TMP_DIR"
TMP_DIR=""

echo
echo "[+] Best mirrors:"
cat "${TMP}.sorted"

echo
echo "[+] Writing optimized mirrorlist..."

if [[ -f "$OUTPUT" ]]; then
    BACKUP="${OUTPUT}.backup-$(date +%Y%m%d_%H%M%S)"
    echo "[+] Backing up existing mirrorlist to $BACKUP..."
    sudo cp "$OUTPUT" "$BACKUP"
fi

{
    echo "## Generated by ALPS"
    echo

    cut -d'|' -f2 "${TMP}.sorted" \
    | while read -r line; do
        echo "Server = $line"
    done

} | sudo tee "$OUTPUT" >/dev/null

echo
echo "[+] Adding repository to pacman.conf..."

if ! grep -q "^\[archlinuxcn\]" /etc/pacman.conf; then
    {
        echo
        echo "[archlinuxcn]"
        echo "Include = /etc/pacman.d/archlinuxcn-mirrorlist"
    } | sudo tee -a /etc/pacman.conf >/dev/null
fi

echo
echo "[+] Initializing pacman keys..."

sudo pacman-key --init

echo
echo "[+] Importing archlinuxcn key..."

sudo pacman-key --recv-keys 3056513887B78AEB --keyserver keyserver.ubuntu.com || \
sudo pacman-key --recv-keys 3056513887B78AEB --keyserver hkps://keyserver.ubuntu.com || \
sudo pacman-key --recv-keys 3056513887B78AEB --keyserver pgp.mit.edu || \
sudo pacman-key --recv-keys 3056513887B78AEB --keyserver keys.openpgp.org

sudo pacman-key --lsign-key 3056513887B78AEB

echo
echo "[+] Installing archlinuxcn-keyring..."

sudo pacman -Sy --noconfirm archlinuxcn-keyring

echo
echo "[+] Syncing pacman..."

sudo pacman -Sy

echo
echo "[+] archlinuxcn setup complete."
