#!/usr/bin/env bash

set -e

ARCH="$(uname -m)"
TOP=5

TMP="$(mktemp)"

MIRROR_URL="https://adrianpriza-ai.github.io/alps-more/archlinuxcn/archlinuxcn-mirrorlist"

OUTPUT="/etc/pacman.d/archlinuxcn-mirrorlist"

echo "[+] Downloading mirrorlist..."

curl -fsSL "$MIRROR_URL" -o "$TMP"

echo
echo "[+] Benchmarking mirrors..."

grep '^Server' "$TMP" \
| sed 's|Server = ||' \
| while read -r url; do

    mirror="${url//\$arch/$ARCH}"

    speed=$(
        curl \
            -o /dev/null \
            -s \
            -w "%{time_total}" \
            --connect-timeout 3 \
            --max-time 8 \
            "${mirror}/core/os/${ARCH}/" \
        2>/dev/null || echo "999"
    )

    echo "$speed $mirror"

done \
| sort -n \
| head -n "$TOP" > "${TMP}.sorted"

echo
echo "[+] Best mirrors:"
cat "${TMP}.sorted"

echo
echo "[+] Writing mirrorlist..."

{
    echo "## Generated by ALPS"
    echo

    awk '{print "Server = " $2}' "${TMP}.sorted"

} | sudo tee "$OUTPUT" >/dev/null

echo
echo "[+] Adding repository to pacman.conf..."

if ! grep -q "^\[archlinuxcn\]" /etc/pacman.conf; then
    {
        echo
        echo "[archlinuxcn]"
        echo "Include = /etc/pacman.d/archlinuxcn-mirrorlist"
    } | sudo tee -a /etc/pacman.conf >/dev/null
fi

echo
echo "[+] Initializing pacman keys..."

sudo pacman-key --init

echo
echo "[+] Importing archlinuxcn key..."

sudo pacman-key \
    --recv-keys 3056513887B78AEB \
    --keyserver keyserver.ubuntu.com

sudo pacman-key --lsign-key 3056513887B78AEB

echo
echo "[+] Installing archlinuxcn-keyring..."

sudo pacman -Sy --noconfirm archlinuxcn-keyring

echo
echo "[+] Syncing pacman..."

sudo pacman -Sy

echo
echo "[+] archlinuxcn setup complete."
